// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfvGONUT3xAGj_V9HRV8Yd82-b9nw0RJg',
    appId: '1:905633992670:web:205f3276afa0bdc310d74f',
    messagingSenderId: '905633992670',
    projectId: 'fb-proj-rivaan-ranawat',
    authDomain: 'fb-proj-rivaan-ranawat.firebaseapp.com',
    storageBucket: 'fb-proj-rivaan-ranawat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZcLHndej8b2QuVdVjSZjFA0oG6bgUPg',
    appId: '1:905633992670:android:4b65fb213e6680f410d74f',
    messagingSenderId: '905633992670',
    projectId: 'fb-proj-rivaan-ranawat',
    storageBucket: 'fb-proj-rivaan-ranawat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZotLdV_T5rjsqXUev-a0zb4l9-Kma8wc',
    appId: '1:905633992670:ios:515f93577324362110d74f',
    messagingSenderId: '905633992670',
    projectId: 'fb-proj-rivaan-ranawat',
    storageBucket: 'fb-proj-rivaan-ranawat.appspot.com',
    iosBundleId: 'com.example.instaCloneFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZotLdV_T5rjsqXUev-a0zb4l9-Kma8wc',
    appId: '1:905633992670:ios:3f4dfa6759995b0710d74f',
    messagingSenderId: '905633992670',
    projectId: 'fb-proj-rivaan-ranawat',
    storageBucket: 'fb-proj-rivaan-ranawat.appspot.com',
    iosBundleId: 'com.example.instaCloneFirebase.RunnerTests',
  );
}
